services:
  - type: web
    name: quantum-health-server
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
